# This is a basic workflow that is triggered by scheduler

name: Schedule triggered workflow

# Workflow runs when triggered by scheduler.

on:
  schedule:
    - cron: "46 8,17 * * 1,2,4"
        
    - cron: "30 12,13 * * 1,2,4"
        
    - cron: "46 8,17 * * 3,5"
        
    - cron: "30 12,13 * * 3,5"
        

# A workflow run that starts a script
jobs: 
  # the name of a job
  run_lola_run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:  # Define environment variables
      TOKEN: ${{ secrets.TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout your repository (if not already checked out)
    - name: Checkout code
      uses: actions/checkout@v2

    # Determine AT_HOME based on the scheduled day of the week
    - name: Determine AT_HOME
      id: at_home
      run: echo "::set-output name=value::$(python3 -c "import datetime; today = datetime.date.today(); print('true' if today.weekday() in [2, 4] else 'false')")"

    # Runs a script
    - name: Run a script
      run: python3 bycode_automation.py --at_home ${{ steps.at_home.outputs.value }}
