# This is a basic workflow that is triggered by scheduler

name: Schedule triggered workflow

# Workflow runs when triggered by scheduler.

on:
  workflow_dispatch:
  schedule:
    - cron: "46 6,15 * * 1,2,3,4,5"
      # timezone: 'Europe/Brussels'
      env:
        TZ: 'Europe/Brussels'
        
    - cron: "30 10 * * 1,2,3,4,5"
      # timezone: 'Europe/Brussels'
      env:
        TZ: 'Europe/Brussels'

    - cron: "10 11 * * 1,2,3,4,5"
      env:
        TZ: 'Europe/Brussels'

jobs: 
  # the name of a job
  run_lola_run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout your repository (if not already checked out)
    - name: Set Timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Europe/Brussels"
        timezoneMacos: "Europe/Brussels"
        timezoneWindows: "Brussels Standard Time"
            
    
    - name: Checkout code
      uses: actions/checkout@v3

        # Runs a script
    - name: Run a script
      run: python3 becode_automation.py
      env:
        TOKEN: ${{ secrets.TOKEN }}

    # Print the contents of the my_script.log file
    - name: Print the contents of the my_script.log file
      run: cat $GITHUB_WORKSPACE/my_script.log
