# This is a basic workflow that is triggered by scheduler

name: Schedule triggered workflow

# Workflow runs when triggered by scheduler.

on:
  workflow_dispatch:
    timezone: 'Europe/Brussels'
  schedule:
    - cron: "46 8,17 * * 1,2,4"
      # timezone: 'Europe/Brussels'
      env:
        TZ: 'Europe/Brussels'
        AT_HOME: "false"
        
    - cron: "30 12,13 * * 1,2,4"
      # timezone: 'Europe/Brussels'
      env:
        TZ: 'Europe/Brussels'
        AT_HOME: "false"
        
    - cron: "46 8,17 * * 3,5"
      # timezone: 'Europe/Brussels'
      env:
        TZ: 'Europe/Brussels'
        AT_HOME: "true"
        
    - cron: "30 12,13 * * 3,5"
      # timezone: 'Europe/Brussels'
      env:
        TZ: 'Europe/Brussels'
        AT_HOME: "true"
        

jobs: 
  # the name of a job
  run_lola_run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout your repository (if not already checked out)
    - name: Set Timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Europe/Brussels"
        timezoneMacos: "Europe/Brussels"
        timezoneWindows: "Brussels Standard Time"
            
    
    - name: Checkout code
      uses: actions/checkout@v3

    # Determine the value of AT_HOME based on the schedule
    - name: Set AT_HOME
      run: |
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          if [[ "${{ github.event.schedule }}" == *"Wed"* || "${{ github.event.schedule }}" == *"Fri"* ]]; then
            echo "AT_HOME=true" >> $GITHUB_ENV
          else
            echo "AT_HOME=false" >> $GITHUB_ENV
          fi
        fi

    # Runs a script
    - name: Run a script
      run: python3 becode_automation.py
      env:
        AT_HOME: ${{ env.AT_HOME }}
        TOKEN: ${{ secrets.TOKEN }}

    # Print the contents of the my_script.log file
    - name: Print the contents of the my_script.log file
      run: cat $GITHUB_WORKSPACE/my_script.log
